// Basing it off artist's names is a bit iffy.
// Could probably get a list of the artist's Spotify IDs instead
export const artistNames = [
    'SAM FENDER',
    'FOALS',
    'BILLIE EILISH',
    'THE KILLERS',
    'BICEP LIVE',
    'HOLLY HUMBERSTONE',
    'RINA SAWAYAMA',
    'BECKY HILL',
    'DECLAN MCKENNA',
    'BAKAR',
    'SUB FOCUS B2B DIMENSION',
    'LOYLE CARNER',
    'ARLO PARKS',
    'LANCEY FOUX',
    'SEA GIRLS',
    'ANDY C',
    'ARTEMAS',
    'AUSTIN MILLZ',
    'BABY QUEEN',
    'BZ',
    'CAITY BASER',
    'CENTRAL CEE',
    'CHARLIE TEE',
    'CHASE ATLANTIC',
    'CLAVISH',
    'COIN',
    'D DOUBLE E',
    'DJ TARGET',
    'DON BROCO',
    'DYLAN JOHN THOMAS',
    'EASY LIFE',
    'EKKSTACY',
    'ELIZA ROSE',
    'ENGLISH TEACHER',
    'ETHEL CAIN',
    'FINN FOXELL',
    'FRANK TURNER & THE SLEEPING SOULS',
    'FRANKIE STEW & HARVEY GUNN',
    'FRICTION',
    'GAMES WE PLAY',
    'GEORGIA',
    'GIANT ROOKS',
    "GIRLS DON'T SYNC",
    'GRAPHIC NATURE',
    'GRYFFIN',
    'HARRIET JAXXON',
    'HEDEX',
    'HIGH VIS',
    'HOT MILK',
    'IMAGINE DRAGONS',
    'INHALER',
    'J FADO',
    'JAGUAR',
    'JAMIE WEBSTER',
    'JBEE',
    'JESSE JO STARK',
    'JOESEF',
    'K-TRAP',
    'KENNY ALLSTAR',
    'KENNYHOOPLA',
    'KILLOWEN',
    'KNOCKED LOOSE',
    'KOVEN',
    'LEWIS CAPALDI',
    'LF SYSTEM',
    'LIL TJAY',
    'LOVEJOY',
    'MAGNOLIA PARK',
    'MALAKI',
    'MEEKZ',
    'MEET ME @ THE ALTAR',
    'METRIK',
    'MIDWXST',
    'MIMI WEBB',
    'MK',
    'MOTHER MOTHER',
    'MUNA',
    'NESSA BARRETT',
    'NIEVE ELLA',
    'NIPPA',
    'NOISY',
    'NORMANDIE',
    'NOTHING BUT THIEVES',
    'PALAYE ROYALE',
    'PINKSHIFT',
    'PROPH',
    'QUEEN MILLZ',
    'ROYEL OTIS',
    'SAINTE',
    'SAMMY VIRGI',
    'SCOWL',
    'SHASIMONE',
    'SHY FX',
    'SLEEP TOKEN',
    'SLOWTHAI',
    'SONGER',
    'SOULECTA',
    'STEVE LACY',
    'TEMZ',
    'THE AMAZONS',
    'THE LAST DINNER PARTY',
    'THE MURDER CAPITAL',
    'THE SNUTS',
    'TION WAYNE',
    'TOM ODELL',
    'TRIPPIE REDD',
    'TV GIRL',
    'VIBE CHEMISTRY',
    'VISTAS',
    'WALLICE',
    'WET LEG',
    'YARD ACT',
    'YONAKA',
    'YOU ME AT SIX',
    'YUNG LEAN',
    'ZAND',
];
